// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZdQjUj8PGCoZBSn8vUO_tHLxviqLUfQ',
    appId: '1:585365689665:web:4998e202c73a53c8bd7dc0',
    messagingSenderId: '585365689665',
    projectId: 'fir-demo-21b60',
    authDomain: 'fir-demo-21b60.firebaseapp.com',
    storageBucket: 'fir-demo-21b60.appspot.com',
    measurementId: 'G-2T2ZM0V9V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaB1HnR-g7tE6M9Sb5PDOB6pED_z5Kflc',
    appId: '1:585365689665:android:30c47da593f697c2bd7dc0',
    messagingSenderId: '585365689665',
    projectId: 'fir-demo-21b60',
    storageBucket: 'fir-demo-21b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgbkJeJXmYf2eu0RgpyZMKSLP4qyIXeqE',
    appId: '1:585365689665:ios:dff731ab637d6ea6bd7dc0',
    messagingSenderId: '585365689665',
    projectId: 'fir-demo-21b60',
    storageBucket: 'fir-demo-21b60.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgbkJeJXmYf2eu0RgpyZMKSLP4qyIXeqE',
    appId: '1:585365689665:ios:257ae4c51e055584bd7dc0',
    messagingSenderId: '585365689665',
    projectId: 'fir-demo-21b60',
    storageBucket: 'fir-demo-21b60.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
